### ISSUE TITLE
Unexpected bump failure notifications (in fork)

### ISSUE THREAD

**Issue by netskink** [ZOSOpenTools/metaport#49]
Hello

I have an email regarding the new bump failure.  I don't really understand why they occur.  Could someone talk to me about this:

https://github.com/netskink/metaport/actions/runs/7232632116

I want to make sure I can avoid the failures.

John

**Comment by v1gnesh** [comment]
Ah yes, I get these too when I have a fork of a repo that has the bump workflow in it.
Just rename `.github` to `.gothub` until you're ready to let Actions kick in.

**Comment by netskink** [comment]
ahh, many thanks.  

I wonder if there is a way to "enable" actions in the fork without getting the messages by stubbing stuff in the forks settings.

Any docs on bump, actions, and related content you all advise to read?

**Comment by v1gnesh** [comment]
Here's the gist of what bump does - https://github.com/ZOSOpenTools/gitport/pull/74

I could be wrong, but I think it gets complicated (trying to make the "as is" Action work in a fork).
Because the fork will then have workflows that are specific to the fork, and you can't send it as a PR until it's exactly what the target repo needs.

Since it isn't possible to have a workflow _only_ in one place (covering the whole org), we need to have a `bump.yml` in all repos, and that then uses [this](https://github.com/ZOSOpenTools/meta/blob/main/actions/action.yml) as a reusable sub-workflow.

**Comment by netskink** [comment]
Hello V1gnesh,

Ok.  Good deal.  I appreciate the info.  I wonder how to summarize all this info.  I can close the issue, but the info needs to be elevated.  I wonder if a section in the docs/site under developer notes would be a good place.

**Comment by netskink** [comment]
Many thanks!

**Comment by v1gnesh** [comment]
Yup, doc update is needed. But I'm holding off on it as I have this unreasonable aversion towards front end stuff lol.
Plus, if I ever get to it, I would like to give the docs site a makeover, making it look like a mix of [this](https://web.archive.org/web/20230605031319/https://zos-hot-topics.com/2022/rest-enabled-bcpii/) & [this](https://developer.ibm.com/tutorials/integrate-enterprise-vault-ibm-cloud-hyper-protect-crypto-services/).

@IgorTodorovskiIBM @MikeFultonDev - please flag to someone in IBM - the [zos hot topics site](https://zos-hot-topics.com/2022/rest-enabled-bcpii/) is dead :smiling_face_with_tear:
